name: Build and Push Multiple Docker Images

# Grant the necessary permissions
permissions:
  contents: read
  packages: write

on:
  push:
    paths:
      - "Distro Testing/Dockerfile"
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at 00:00 UTC

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [
          { name: "ubuntu-24.04", base: "ubuntu:24.04", pkg: "apt" },
          { name: "ubuntu-22.04", base: "ubuntu:22.04", pkg: "apt" },
          { name: "debian-12",    base: "debian:12",    pkg: "apt" },
          { name: "linuxmint-22", base: "linuxmintd/mint22.1-amd64", pkg: "apt" },
          { name: "linuxmint-21", base: "linuxmintd/mint21.3-amd64", pkg: "apt" },
          { name: "fedora-41",    base: "fedora:41",    pkg: "dnf" },
          { name: "fedora-40",    base: "fedora:40",    pkg: "dnf" },
          { name: "almalinux-9",  base: "almalinux:9",  pkg: "dnf" },
          { name: "almalinux-8",  base: "almalinux:8",  pkg: "dnf" },
          { name: "rocky-9",      base: "rockylinux:9", pkg: "dnf" },
          { name: "rocky-8",      base: "rockylinux:8", pkg: "dnf" },
          { name: "opensuse-leap-15.6", base: "opensuse/leap:15.6", pkg: "zypper" },
          { name: "opensuse-tumbleweed", base: "opensuse/tumbleweed", pkg: "zypper" },
          { name: "arch",         base: "archlinux:latest", pkg: "pacman" }
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and Push Docker Image for ${{ matrix.distro.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: "Distro Testing/Dockerfile"
          build-args: |
            BASE_IMAGE=${{ matrix.distro.base }}
            PKG_MANAGER=${{ matrix.distro.pkg }}
          tags: ghcr.io/${{ github.repository_owner }}/nadekobot-testing-${{ matrix.distro.name }}
          push: true
